# action.yml
name: Setup lenv
description: "Installs Lenv"
runs:
  using: "composite"
  steps:
    - name: Install Lenv
      shell: bash
      run: |
        wget https://github.com/mah0x211/lenv/releases/download/v0.6.0/lenv_Linux_x86_64.tar.gz -O ./lenv.tar.gz
        tar xvzf ./lenv.tar.gz
        mkdir -p $HOME/.local/bin
        mv ./lenv $HOME/.local/bin
        echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
        lenv setup
        lenv path bin >> $GITHUB_PATH
        echo "LUA_PATH=$(lenv path lualib)" >> $GITHUB_ENV
        echo "LUA_CPATH=$(lenv path luaclib)" >> $GITHUB_ENV
        lenv fetch
