name: test

on:
    push:
      branches:
        - '**'
      paths-ignore:
        - '**.md'
        - 'LICENSE'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup lenv
      uses: ./.github/actions/setup-lenv
    -
      name: Install Lua and Luarocks
      run: lenv install latest:latest
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Lua 5.1"
            command: "install 5.1.:latest linux"
          - name: "Lua 5.2"
            command: "install 5.2.:latest linux"
          - name: "Lua 5.3"
            command: "install 5.3.:latest linux"
          - name: "Lua 5.4"
            command: "install 5.4.:latest"
          - name: "LuaJIT 2.1"
            command: "install-lj v2.1:latest"
    name: Test ${{ matrix.name }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup lenv
      uses: ./.github/actions/setup-lenv
    -
      name: Install Lua and Luarocks
      run: lenv ${{ matrix.command }}
    -
      name: Install
      run: |
        luarocks make
    -
      name: Install Tools
      run: |
        luarocks install testcase
        luarocks install luacov
        luarocks install exec
        luarocks install io-fileno
        luarocks install io-tofile
        luarocks install io-wait
    -
      name: Run Test
      run: |
        testcase --coverage ./test/
    -
      name: Upload lua coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./luacov.report.out
        flags: unittests
    # -
    #   name: Generate coverage reports
    #   run: |
    #     sh ./covgen.sh
    # -
    #   name: Upload c coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     files: ./coverage/lcov.info
    #     flags: unittests
